apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: gateway
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: gateway
              servicePort: 80
          - path: /bs
            backend:
              serviceName: booking-service
              servicePort: 80